/*
    ClinicQ - reference/sample data (SQL Server)
    Idempotent: only inserts when the target table is empty.
    Password for every seeded user is "Passw0rd!" (PBKDF2-SHA256, 100k iterations).
    Transactional sample data (appointments, invoices) is generated by the application's
    DataSeeder on first start so that the demo calendar is always relative to "today".
*/
SET NOCOUNT ON;
GO

/* ---------------------------------------------------------------- Branches */
IF NOT EXISTS (SELECT 1 FROM dbo.Branches)
BEGIN
    INSERT INTO dbo.Branches (Code, Name, AddressLine, City, State, PostalCode, Phone, TimeZoneId, TaxRatePercent, IsActive)
    VALUES
        ('SPI', 'Springfield Clinic',  '410 E Monroe St',   'Springfield', 'IL', '62701', '(217) 555-0140', 'Central Standard Time', 0.00, 1),
        ('CHI', 'Chicago Loop Clinic', '120 S Riverside Pl','Chicago',     'IL', '60606', '(312) 555-0188', 'Central Standard Time', 1.25, 1),
        ('PEO', 'Peoria Clinic',       '530 NE Glen Oak Ave','Peoria',     'IL', '61637', '(309) 555-0112', 'Central Standard Time', 0.00, 1);
END
GO

/* --------------------------------------------------------- BranchSlotRules */
IF NOT EXISTS (SELECT 1 FROM dbo.BranchSlotRules)
BEGIN
    INSERT INTO dbo.BranchSlotRules (BranchId, OpenTime, CloseTime, SlotDurationMinutes, WorkingDaysMask, MaxBookingsPerSlot, MinLeadTimeHours, MaxAdvanceDays)
    SELECT Id, '08:00', '17:00', 30, 31, 1, 1, 60 FROM dbo.Branches WHERE Code = 'SPI'
    UNION ALL
    SELECT Id, '07:30', '18:30', 20, 63, 2, 2, 90 FROM dbo.Branches WHERE Code = 'CHI'
    UNION ALL
    SELECT Id, '09:00', '16:00', 30, 31, 1, 1, 45 FROM dbo.Branches WHERE Code = 'PEO';
END
GO

/* ----------------------------------------------------------------- Doctors */
IF NOT EXISTS (SELECT 1 FROM dbo.Doctors)
BEGIN
    INSERT INTO dbo.Doctors (BranchId, FullName, Specialty, Email, LicenseNumber, IsActive)
    SELECT b.Id, d.FullName, d.Specialty, d.Email, d.LicenseNumber, 1
    FROM (VALUES
        ('SPI', 'Dr. Anita Patel',     'Family Medicine',  'anita.patel@clinicq.example',     'IL-MD-104422'),
        ('SPI', 'Dr. Marcus Whitfield','Internal Medicine','marcus.whitfield@clinicq.example','IL-MD-118730'),
        ('CHI', 'Dr. Elena Rossi',     'Pediatrics',       'elena.rossi@clinicq.example',     'IL-MD-120915'),
        ('CHI', 'Dr. Samuel Okafor',   'Cardiology',       'samuel.okafor@clinicq.example',   'IL-MD-098211'),
        ('CHI', 'Dr. Grace Lindqvist', 'Dermatology',      'grace.lindqvist@clinicq.example', 'IL-MD-131004'),
        ('PEO', 'Dr. Daniel Nguyen',   'Family Medicine',  'daniel.nguyen@clinicq.example',   'IL-MD-115688')
    ) AS d (BranchCode, FullName, Specialty, Email, LicenseNumber)
    JOIN dbo.Branches b ON b.Code = d.BranchCode;
END
GO

/* ------------------------------------------------------------- FeeSchedule */
IF NOT EXISTS (SELECT 1 FROM dbo.FeeSchedule)
BEGIN
    INSERT INTO dbo.FeeSchedule (BranchId, ServiceCode, Description, Amount, IsActive, EffectiveFrom)
    SELECT b.Id, f.ServiceCode, f.Description, f.Amount * m.Multiplier, 1, '2024-01-01'
    FROM (VALUES
        ('CONSULT',  'New patient consultation',       120.00),
        ('FOLLOWUP', 'Follow-up visit',                 75.00),
        ('LAB-CBC',  'Complete blood count',             45.00),
        ('LAB-LIPID','Lipid panel',                      65.00),
        ('XRAY',     'X-ray, single view',              150.00),
        ('VACCINE',  'Vaccination administration',       60.00),
        ('ECG',      'Electrocardiogram',                95.00)
    ) AS f (ServiceCode, Description, Amount)
    CROSS JOIN (VALUES ('SPI', 1.00), ('CHI', 1.20), ('PEO', 0.95)) AS m (BranchCode, Multiplier)
    JOIN dbo.Branches b ON b.Code = m.BranchCode;
END
GO

/* ------------------------------------------------------------------- Users */
IF NOT EXISTS (SELECT 1 FROM dbo.Users)
BEGIN
    INSERT INTO dbo.Users (Username, DisplayName, Email, PasswordHash, Role, BranchId, IsActive)
    VALUES
        ('admin',     'System Administrator', 'admin@clinicq.example',     'PBKDF2-SHA256$100000$hz2QjIvmF5FW+HoDgnPojQ==$QnnKhvoppxfweDKqU+kcD0sqgxS4Ul05OsgiHBgX0JU=', 'Admin',        NULL, 1),
        ('reception', 'Front Desk',           'reception@clinicq.example', 'PBKDF2-SHA256$100000$bKU1oVcJWlZPvglcqz05iQ==$oChThqffO/eAEGkbE1fQVDDKjvDbRTecWW8dM5IMZUk=', 'Receptionist', (SELECT Id FROM dbo.Branches WHERE Code = 'SPI'), 1),
        ('drpatel',   'Dr. Anita Patel',      'anita.patel@clinicq.example','PBKDF2-SHA256$100000$jtU/wIqCV4A6jNsrpjIMvw==$ZjV3EHmbgQWrvHXpTUI0RzAZiCY+SNbFs/o9F/dw5f8=', 'Doctor',       (SELECT Id FROM dbo.Branches WHERE Code = 'SPI'), 1),
        ('billing',   'Billing Office',       'billing@clinicq.example',   'PBKDF2-SHA256$100000$9EWemxsEFmkMWvC7s+4Hbg==$0u11syrwj1Me7gvGsjwCmD2ibZu3LC5jMih6p7+wpeI=', 'Billing',      NULL, 1);
END
GO

/* ---------------------------------------------------------------- Patients */
IF NOT EXISTS (SELECT 1 FROM dbo.Patients)
BEGIN
    INSERT INTO dbo.Patients (Mrn, FirstName, LastName, DateOfBirth, Gender, Email, Phone, AddressLine, City, State, PostalCode, Allergies, CreatedAt)
    VALUES
        ('MRN-100001', 'Olivia',  'Bennett',  '1986-03-14', 'Female', 'olivia.bennett@example.com',  '(217) 555-0101', '12 Oak St',       'Springfield', 'IL', '62704', 'Penicillin', SYSUTCDATETIME()),
        ('MRN-100002', 'Liam',    'Carter',   '1979-11-02', 'Male',   'liam.carter@example.com',     '(217) 555-0102', '88 Maple Ave',    'Springfield', 'IL', '62702', NULL,          SYSUTCDATETIME()),
        ('MRN-100003', 'Sophia',  'Diaz',     '2016-06-21', 'Female', 'sophia.diaz@example.com',     '(312) 555-0103', '400 W Lake St',   'Chicago',     'IL', '60606', 'Peanuts',     SYSUTCDATETIME()),
        ('MRN-100004', 'Noah',    'Eriksen',  '1954-01-30', 'Male',   'noah.eriksen@example.com',    '(312) 555-0104', '9 Wells St',      'Chicago',     'IL', '60610', NULL,          SYSUTCDATETIME()),
        ('MRN-100005', 'Ava',     'Foster',   '1992-09-09', 'Female', 'ava.foster@example.com',      '(309) 555-0105', '71 Main St',      'Peoria',      'IL', '61602', 'Latex',       SYSUTCDATETIME()),
        ('MRN-100006', 'Ethan',   'Garcia',   '2001-04-17', 'Male',   'ethan.garcia@example.com',    '(309) 555-0106', '23 River Rd',     'Peoria',      'IL', '61603', NULL,          SYSUTCDATETIME()),
        ('MRN-100007', 'Mia',     'Hoffmann', '1948-12-05', 'Female', 'mia.hoffmann@example.com',    '(217) 555-0107', '5 Lincoln Pl',    'Springfield', 'IL', '62703', 'Sulfa drugs', SYSUTCDATETIME()),
        ('MRN-100008', 'James',   'Ibrahim',  '1988-07-23', 'Male',   'james.ibrahim@example.com',   '(312) 555-0108', '250 N State St',  'Chicago',     'IL', '60654', NULL,          SYSUTCDATETIME()),
        ('MRN-100009', 'Isabella','Jensen',   '1995-02-11', 'Female', 'isabella.jensen@example.com', '(217) 555-0109', '17 Elm Ct',       'Springfield', 'IL', '62704', NULL,          SYSUTCDATETIME()),
        ('MRN-100010', 'Lucas',   'Kim',      '2013-10-28', 'Male',   'lucas.kim@example.com',       '(312) 555-0110', '60 E Erie St',    'Chicago',     'IL', '60611', 'Eggs',        SYSUTCDATETIME()),
        ('MRN-100011', 'Charlotte','Lopez',   '1970-05-19', 'Female', 'charlotte.lopez@example.com', '(309) 555-0111', '14 Prospect Rd',  'Peoria',      'IL', '61604', NULL,          SYSUTCDATETIME()),
        ('MRN-100012', 'Benjamin','Murphy',   '1963-08-08', 'Male',   'benjamin.murphy@example.com', '(217) 555-0112', '33 Capitol Ave',  'Springfield', 'IL', '62701', 'Aspirin',     SYSUTCDATETIME());
END
GO
